apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: .
    contents:
      - path: devlib
        git:
          url: https://fj.ktbcloud.com/bkenks/lib_compose.git
          ref: main
        newRootPath: src
