services:
  db:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  pgadmin:
    environment:
      PGADMIN_DEFAULT_PASSWORD: password

      # Don't require the user to login
      PGADMIN_CONFIG_SERVER_MODE: 'False'

      # Don't require a "master" password after logging in
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - '5051:80'
