---
name: samba
services:
  samba:
    image: dockurr/samba:4.23.5
    container_name: samba
    user: "0:0"
    volumes:
      - ${DOCKER_VOLUMES}:/storage/DOCKER_BINDS
      - /var/lib/docker/volumes:/storage/DOCKER_NAMED
    environment:
      NAME: mnt
      USER: ${SMB_USER}
      PASS: ${SMB_PASS}
    ports:
      - '445:445'
    restart: unless-stopped
