// Renders the three generated config files in this directory:
//
//   config.yaml          → mounted read-only into pangolin at /app/config/config.yml
//   dynamic_config.yaml  → mounted read-only into traefik  at /etc/traefik/dynamic_config.yml
//   traefik_config.yaml  → mounted read-only into traefik  at /etc/traefik/traefik_config.yml
//
// All operational knowledge lives in platform/edge/pangolin.libsonnet (safe_dump strips
// comments, so the yaml carries only a DO-NOT-EDIT header); this instance's knobs live in
// ../instance.libsonnet. Edit those, not the yaml.
//
// privateConfig.yml, also in this directory, is HAND-WRITTEN and not generated by this file.
local pangolin = import '../../pangolin.libsonnet';

pangolin.configs(import '../instance.libsonnet')
