services:
  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:?err}

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: briankenkel.t@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS:?err}

      # Require Login Flag (True=Required)
      PGADMIN_CONFIG_SERVER_MODE: 'True'

      # Require Master Password (True=Required)
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'True'
