services:
  app:
    image: ghcr.io/lukegus/termix:${TERMIX__VERS_TAG:?err}
    depends_on:
      guacd:
        condition: service_started
    volumes:
      - termix-data:/app/data
    env_file:
      - "../container-envs/${TERMIX__NAME:?err}.env"
    networks:
      - default
      - proxy
    restart: on-failure:${TERMIX__MAX_RESTART_ATTEMPS:?err}
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8080/" ]
      interval: 15s
      timeout: 5s
      retries: 10
    labels:
      traefik.enable: 'true'
      traefik.http.routers.termix.rule: 'Host(`termix.homektb.com`)'
      traefik.http.routers.termix.entrypoints: websecure
      traefik.http.routers.termix.tls: 'true'
      traefik.http.services.termix.loadbalancer.server.port: '8080'
    expose:
      - '8080'

  guacd:
    image: docker.io/guacamole/guacd:${GUACD__VERS_TAG:?err}
    env_file:
      - "../container-envs/${GUACD__NAME:?err}.env"
    restart: on-failure:${GUACD__MAX_RESTART_ATTEMPS:?err}
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 4822 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
    expose:
      - '4822'

networks:
  proxy:
    name: shared-proxy
    external: true

volumes:
  termix-data: {}
