---
name: actual-budget-production

services:
  actual-budget:
    container_name: ${COMPOSE_PROJECT_NAME}_actual-budget
    volumes:
      - ${DOCKER_VOLUMES}/apps/actual-budget/data:/data
    ports:
      - '5006:5006'
