#!/bin/sh
# Assembles agent config at startup from AGENT_SERVICES + per-service fragments in
# /agent/templates/ (generated by services.jsonnet from registry.libsonnet, not here).
set -eu

: "${AGENT_HOST:?AGENT_HOST is required (host name; drives \${AGENT_HOST} secret-path subs)}"
: "${AGENT_SERVICES:?AGENT_SERVICES is required (space/comma list of services from templates/)}"
: "${INFISICAL_ADDRESS:?INFISICAL_ADDRESS is required (public URL by default; per-host override)}"

templates="/agent/templates"
config="/tmp/agent.generated.yaml"
cred_id="/dev/shm/agent.client-id"
cred_secret="/dev/shm/agent.client-secret"

# Write from env only if provided; otherwise leave a pre-written file (Ansible/control-plane path) untouched.
if [ -n "${INFISICAL_CLIENT_ID:-}" ]; then
  printf '%s' "$INFISICAL_CLIENT_ID" > "$cred_id"
fi
if [ -n "${INFISICAL_CLIENT_SECRET:-}" ]; then
  printf '%s' "$INFISICAL_CLIENT_SECRET" > "$cred_secret"
fi
if [ ! -s "$cred_id" ] || [ ! -s "$cred_secret" ]; then
  echo "infisical-agent: missing $cred_id or $cred_secret" >&2
  echo "  provide INFISICAL_CLIENT_ID / INFISICAL_CLIENT_SECRET (env) or pre-write the files" >&2
  exit 1
fi
chmod 0600 "$cred_id" "$cred_secret" 2>/dev/null || true

cat > "$config" <<EOF
infisical:
  address: "${INFISICAL_ADDRESS}"
  exit-after-auth: false
  revoke-credentials-on-shutdown: false

auth:
  type: "universal-auth"
  config:
    client-id: "${cred_id}"
    client-secret: "${cred_secret}"
    remove_client_secret_on_read: true

templates:
EOF

services=$(printf '%s' "$AGENT_SERVICES" | tr ',' ' ')

for svc in $services; do
  frag="$templates/${svc}.yaml"
  [ -f "$frag" ] || { echo "infisical-agent: unknown service '$svc' (no $frag)" >&2; exit 1; }
  # Infisical's template engine has no env access, so ${AGENT_HOST} baked into a fragment's
  # secret path is substituted here (no-op for fragments without it).
  sed "s|\${AGENT_HOST}|${AGENT_HOST}|g" "$frag" >> "$config"
done

# Docker healthcheck can't read `docker logs`, so mirror the agent's stdout to
# /tmp/agent.log; tail -f re-streams it to stdout too. exec keeps the agent PID 1.
#
# Health must reflect CURRENT state: the agent is silent on success, so an append-only
# log can't tell "ok now" from "errored earlier". Instead stamp /tmp/agent.last_err on
# every ERR/FTL/PNC line; compose/agent.yml's healthcheck flags unhealthy only while
# that stamp is recent, so it self-heals once errors stop without a restart.
log="/tmp/agent.log"
err_stamp="/tmp/agent.last_err"
: > "$log"
rm -f "$err_stamp"
tail -f "$log" &

# *ERR* also matches ANSI-wrapped zerolog levels; safe against false positives since
# ERR/FTL/PNC are uppercase-only and never appear in mixed-case text like "APIError".
tail -f "$log" | while IFS= read -r line; do
  case "$line" in
    *ERR*|*FTL*|*PNC*) date +%s > "$err_stamp" ;;
  esac
done &

echo "infisical-agent: $AGENT_HOST | address $INFISICAL_ADDRESS | services: $services"
exec infisical agent --config "$config" >> "$log" 2>&1
