[[server]]
name = "biggy"
[server.config]
address = "http://biggy:8120"

##

[[server]]
name = "blueberrypi"
[server.config]
address = "http://192.168.30.156:8120"

##

[[server]]
name = "littlebuddy"
description = "Control Plane - Runs stack.infra, stack.biz-ops, and other critical services."
[server.config]
address = "host.docker.internal:8120"
region = "cincinnati, oh"
enabled = true

##

[[server]]
name = "maboi"
description = "Hetzner VPS CPX11"
tags = ["vps"]
[server.config]
address = "maboi:8120"
region = "ashland, va"
enabled = true

##

[[server]]
name = "paiki"
[server.config]
address = "plexyandiknowit:8120"
region = "cincinnati, oh"
enabled = true

##

[[stack]]
name = "client_couch-potatoes_prod"
tags = ["client", "stackform"]
[stack.config]
server = "maboi"
linked_repo = "client_couch-potatoes_website"
run_directory = "./compose"
file_paths = ["compose.prod.yaml"]
registry_provider = "ghcr.io"
registry_account = "bkenks"
post_deploy.command = """
  # Add multiple commands on new lines. Supports comments.
  # bs3 envject PAYLOAD_SECRET \
  # -- docker compose -f docker-compose.prod.yml --profile seed run --rm seed
"""
ignore_services = ["seed"]
environment = """
# Uncomment to seed example data
COMPOSE_PROFILES = seed
"""

##

[[stack]]
name = "client_royalty-hvac_website"
[stack.config]
server = "maboi"
linked_repo = "client_royalty-hvac_website"
reclone = true
run_directory = "./compose"

##

[[stack]]
name = "cloudflared_littlebuddy"
[stack.config]
server = "littlebuddy"
linked_repo = "infra.stacks"
run_directory = "./node/cloudflared"

##

[[stack]]
name = "cloudflared_maboi"
[stack.config]
server = "maboi"
linked_repo = "infra.stacks"
run_directory = "./node/cloudflared"

##

[[stack]]
name = "cloudflared_node"
template = true
[stack.config]
linked_repo = "node"
run_directory = "./cloudflared"

##

[[stack]]
name = "cloudflared_paiki"
[stack.config]
server = "paiki"
linked_repo = "infra.stacks"
run_directory = "./node/cloudflared"

##

[[stack]]
name = "databasus_littlebuddy"
[stack.config]
server = "littlebuddy"
links = [
  "https://databasus.lilbud.homektb.com"
]
poll_for_updates = true
linked_repo = "infra.stacks"
webhook_enabled = false
run_directory = "./node/databasus"
file_paths = [
  "compose.yaml",
  "compose.production.yaml"
]
additional_env_files = [
  { path = "config/production.env", track = true }
]
environment = """
DATABASUS__HOST=lilbud
"""

##

[[stack]]
name = "databasus_maboi"
[stack.config]
server = "maboi"
links = [
  "https://databasus.maboi.homektb.com"
]
poll_for_updates = true
linked_repo = "infra.stacks"
run_directory = "./node/databasus"
file_paths = [
  "compose.yaml",
  "compose.production.yaml"
]
additional_env_files = [
  { path = "config/production.env", track = true }
]
environment = """
DATABASUS__HOST=maboi
"""

##

[[stack]]
name = "databasus_paiki"
[stack.config]
server = "paiki"
links = [
  "https://databasus.paiki.homektb.com"
]
poll_for_updates = true
linked_repo = "infra.stacks"
run_directory = "./node/databasus"
file_paths = [
  "compose.yaml",
  "compose.production.yaml"
]
additional_env_files = [
  { path = "config/production.env", track = true }
]
environment = """
DATABASUS__HOST=paiki
"""

##

[[stack]]
name = "docuseal-prod"
[stack.config]
server = "littlebuddy"
linked_repo = "infra.stacks"
run_directory = "./apps/business/docuseal"

##

[[stack]]
name = "forgejo-prod"
[stack.config]
server = "littlebuddy"
linked_repo = "infra.stacks"
run_directory = "./platform/forgejo"

##

[[stack]]
name = "frappe-production"
[stack.config]
server = "littlebuddy"
linked_repo = "infra.stacks"
run_directory = "./apps/business/frappe"
ignore_services = ["configurator"]

##

[[stack]]
name = "immich-production"
[stack.config]
server = "paiki"
links = ["https://immich.homektb.com"]
linked_repo = "infra.stacks"
run_directory = "./apps/personal/immich"
file_paths = ["compose.yaml"]
env_file_path = "komodo_vars.env"
additional_env_files = [
  { path = "config/production.env", track = true },
  { path = "/dev/shm/immich.env", track = true }
]
compose_cmd_wrapper_include = ["config", "build", "pull", "up", "run"]
environment = """
  # VARIABLE = value
DOCKER_VOLUMES=[[SRV_DOCKER_VOL]]
ROOT_DOMAIN=[[ROOT_DOMAIN]]
"""

##

[[stack]]
name = "infisical"
tags = ["infra"]
[stack.config]
server = "littlebuddy"
linked_repo = "infra.stacks"
run_directory = "./platform/infisical"

##

[[stack]]
name = "infisical-agent_littlebuddy"
tags = ["secret-agent"]
[stack.config]
server = "littlebuddy"
linked_repo = "infra.stacks"
run_directory = "./node/infisical-agent"
environment = """
  # VARIABLE = value
AGENT_HOST=                       littlebuddy
COMPOSE_PROFILES=                 standard
INFISICAL_CLIENT_ID=              [[LITTLEBUDDY__AGENT_CLIENT_ID]]
INFISICAL_CLIENT_SECRET=          [[LITTLEBUDDY__AGENT_CLIENT_SECRET]]
"""

##

[[stack]]
name = "infisical-agent_maboi"
tags = ["secret-agent"]
[stack.config]
server = "maboi"
linked_repo = "infra.stacks"
run_directory = "./node/infisical-agent"
environment = """
  # VARIABLE = value
COMPOSE_PROFILES=               standard
AGENT_HOST=                     maboi
INFISICAL_CLIENT_ID=            [[MABOI__AGENT_CLIENT_ID]]
INFISICAL_CLIENT_SECRET=        [[MABOI__AGENT_CLIENT_SECRET]]
"""

##

[[stack]]
name = "infisical-agent_paiki"
tags = ["secret-agent"]
[stack.config]
server = "paiki"
linked_repo = "infra.stacks"
run_directory = "./node/infisical-agent"
environment = """
COMPOSE_PROFILES=         standard
AGENT_HOST=               paiki
INFISICAL_CLIENT_ID=      [[PAIKI__AGENT_CLIENT_ID]]
INFISICAL_CLIENT_SECRET=  [[PAIKI__AGENT_CLIENT_SECRET]]
"""

##

[[stack]]
name = "infisical-agent_template"
template = true
[stack.config]
linked_repo = "infra"
run_directory = "./infisical-agent"
environment = """
  # VARIABLE = value
COMPOSE_PROFILES=standard
AGENT_HOST=
INFISICAL_CLIENT_ID = 
INFISICAL_CLIENT_SECRET = 
"""

##

[[stack]]
name = "komodo-mcp"
[stack.config]
server = "littlebuddy"
linked_repo = "infra.stacks"
run_directory = "./platform/komodo-mcp"

##

[[stack]]
name = "paperless-production"
[stack.config]
server = "littlebuddy"
linked_repo = "infra.stacks"
run_directory = "./apps/personal/paperless"
env_file_path = "komodo_vars.env"
pre_deploy.command = """
  # Add multiple commands on new lines. Supports comments.
"""
environment = """
  # VARIABLE = value
DOCKER_VOLUMES=[[SRV_DOCKER_VOL]]
"""

##

[[stack]]
name = "postgres-production"
[stack.config]
server = "littlebuddy"
linked_repo = "infra.stacks"
webhook_enabled = false
run_directory = "./databases/postgres"

##

[[stack]]
name = "scriberr-production"
[stack.config]
server = "littlebuddy"
links = ["scriberr.homektb.com"]
linked_repo = "infra.stacks"
run_directory = "./apps/personal/scriberr"
env_file_path = "komodo_vars.env"
environment = """
  # VARIABLE = value
DOCKER_VOLUMES=[[SRV_DOCKER_VOL]]
"""

##

[[stack]]
name = "stackform_website"
tags = ["stackform"]
[stack.config]
server = "maboi"
run_build = true
linked_repo = "stackform_website"
run_directory = "./compose"

##

[[stack]]
name = "stream"
[stack.config]
server = "paiki"
linked_repo = "stream"
run_directory = "./"
file_paths = ["compose.yaml"]
env_file_path = "komodo_vars.env"
ignore_services = ["configarr"]
environment = """
DOCKER_VOLUMES = [[DOCKER_VOLUMES]]
"""

##

[[stack]]
name = "traefik_littlebuddy"
[stack.config]
server = "littlebuddy"
destroy_before_deploy = true
linked_repo = "infra.stacks"
run_directory = "./node/traefik"
extra_args = ["--force-recreate"]
environment = """
AGENT_HOST=   littlebuddy
"""

##

[[stack]]
name = "traefik_maboi"
[stack.config]
server = "maboi"
linked_repo = "infra.stacks"
run_directory = "./node/traefik"
extra_args = ["--force-recreate"]
environment = """
AGENT_HOST=   maboi
"""

##

[[stack]]
name = "traefik_node"
template = true
[stack.config]
linked_repo = "node"
run_directory = "./traefik"
environment = """
AGENT_HOST=   
"""

##

[[stack]]
name = "traefik_paiki"
[stack.config]
server = "paiki"
linked_repo = "infra.stacks"
run_directory = "./node/traefik"
extra_args = ["--force-recreate"]
environment = """
AGENT_HOST=   paiki
"""

##

[[stack]]
name = "woodpecker"
template = true
[stack.config]
linked_repo = "infra"
run_directory = "./woodpecker"

##

[[stack]]
name = "woodpecker-prod"
[stack.config]
server = "littlebuddy"
linked_repo = "infra.stacks"
run_directory = "./platform/woodpecker"

##

[[stack]]
name = "zerobyte_littlebuddy"
[stack.config]
server = "littlebuddy"
links = [
  "https://zerobyte.lilbud.homektb.com"
]
linked_repo = "infra.stacks"
run_directory = "./node/zerobyte"
environment = """
ZEROBYTE__HOST=   lilbud
"""

##

[[stack]]
name = "zerobyte_node"
template = true
[stack.config]
linked_repo = "node"
run_directory = "./zerobyte"
environment = """
ZEROBYTE__HOST=   
"""

##

[[build]]
name = "client_couch-potatoes_website"
[build.config]
builder = "littlebuddy"
linked_repo = "client_couch-potatoes_website"
image_registry = [
  { domain = "ghcr.io", account = "bkenks", organization = "stackform-hq" }
]
build_args = """
NEXT_PUBLIC_DEMO = true
"""

##

[[build]]
name = "client_couch-potatoes_website_seed"
[build.config]
builder = "littlebuddy"
linked_repo = "client_couch-potatoes_website"
dockerfile_path = "Dockerfile.seed"
image_registry = [
  { domain = "ghcr.io", account = "bkenks", organization = "stackform-hq" }
]

##

[[build]]
name = "client_royalty-hvac_website"
[build.config]
builder = "littlebuddy"
linked_repo = "client_royalty-hvac_website"
image_registry = [
  { domain = "ghcr.io", account = "bkenks", organization = "stackform-hq" }
]
build_args = """
NEXT_PUBLIC_DEMO = true
"""

##

[[build]]
name = "stackform_website"
[build.config]
builder = "littlebuddy"
linked_repo = "stackform_website"
image_registry = [
  { domain = "ghcr.io", account = "bkenks", organization = "stackform-hq" }
]
build_args = """
  # VARIABLE = value
NEXT_PUBLIC_SERVER_URL = "https://stackform.app"
"""

##

[[repo]]
name = "apps"
[repo.config]
server = "littlebuddy"
git_account = "bkenks"
repo = "ktbgroup-self-hosted/stack.apps"

##

[[repo]]
name = "biz-ops"
[repo.config]
git_account = "bkenks"
repo = "ktbgroup-self-hosted/stack.biz-ops"

##

[[repo]]
name = "bkenks"
template = true
[repo.config]
git_account = "bkenks"
on_pull.command = """
dcvols -r --uid 1000 --gid 1000
"""

##

[[repo]]
name = "client_couch-potatoes_website"
tags = ["stackform", "client"]
[repo.config]
server = "littlebuddy"
git_provider = "fj.homektb.com"
git_account = "bkenks"
repo = "stackform-hq/client_couch-potatoes_website"

##

[[repo]]
name = "client_royalty-hvac_website"
tags = ["stackform", "client"]
[repo.config]
server = "littlebuddy"
git_provider = "fj.homektb.com"
git_account = "bkenks"
repo = "stackform-hq/client_royalty-hvac_website"

##

[[repo]]
name = "databases"
[repo.config]
server = "littlebuddy"
git_provider = "fj.homektb.com"
git_account = "bkenks"
repo = "ktbgroup-self-hosted/stack.databases"

##

[[repo]]
name = "games"
[repo.config]
server = "biggy"
git_account = "bkenks"
repo = "ktbgroup-self-hosted/stack.games"
on_pull.command = """
# dcvols -r --uid 1000 --gid 1000
"""
environment = """
  # VARIABLE = value
"""

##

[[repo]]
name = "infra"
[repo.config]
git_account = "bkenks"
repo = "ktbgroup-self-hosted/stack.infra"

##

[[repo]]
name = "infra.stacks"
[repo.config]
server = "littlebuddy"
git_provider = "fj.homektb.com"
git_account = "bkenks"
repo = "ktbgroup-self-hosted/infra.stacks"

##

[[repo]]
name = "ktbgroup-self-hosted"
template = true
[repo.config]
git_account = "bkenks"
repo = "ktbgroup-self-hosted/"

##

[[repo]]
name = "network"
[repo.config]
server = "blueberrypi"
builder = "littlebuddy"
git_account = "bkenks"
repo = "ktbgroup-self-hosted/stack.network"
on_pull.command = """
dcvols -r --uid 1000 --gid 1000
"""

##

[[repo]]
name = "node"
[repo.config]
server = "biggy"
git_account = "bkenks"
repo = "ktbgroup-self-hosted/stack.node"

##

[[repo]]
name = "stackform-hq"
template = true
[repo.config]
git_account = "bkenks"
repo = "stackform-hq/"

##

[[repo]]
name = "stackform_website"
[repo.config]
server = "littlebuddy"
git_provider = "fj.homektb.com"
git_account = "bkenks"
repo = "stackform-hq/stackform_website"

##

[[repo]]
name = "stream"
[repo.config]
server = "paiki"
git_account = "bkenks"
repo = "ktbgroup-self-hosted/stack.stream"
environment = """
DOCKER_VOLUMES = [[DOCKER_VOLUMES]]
"""

##

[[procedure]]
name = "Backup Core Database"
description = "Triggers the Core database backup at the scheduled time."
config.schedule = "Every day at 01:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "BackupCoreDatabase", execution.params = {}, enabled = true }
]

##

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
config.schedule = "Every day at 03:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params.skip_auto_update = false, enabled = true }
]

##

[[procedure]]
name = "Global Cleanup"
config.webhook_enabled = false
config.schedule = "Every Sunday at midnight"
config.schedule_timezone = "America/New_York"

[[procedure.config.stage]]
name = "Pruning"
enabled = true
executions = [
  { execution.type = "PruneSystem", execution.params.server = "littlebuddy", enabled = true },
  { execution.type = "PruneSystem", execution.params.server = "maboi", enabled = true },
  { execution.type = "PruneSystem", execution.params.server = "paiki", enabled = true }
]

##

[[procedure]]
name = "Restart: infisical-agent"

[[procedure.config.stage]]
name = "Deploy config"
enabled = true
executions = [
  { execution.type = "DeployStack", execution.params.stack = "infisical-agent_littlebuddy", execution.params.services = [], enabled = true },
  { execution.type = "DeployStack", execution.params.stack = "infisical-agent_maboi", execution.params.services = [], enabled = true },
  { execution.type = "DeployStack", execution.params.stack = "infisical-agent_paiki", execution.params.services = [], enabled = true }
]

[[procedure.config.stage]]
name = "Restart container"
enabled = true
executions = [
  { execution.type = "RestartStack", execution.params.stack = "infisical-agent_littlebuddy", execution.params.services = [], enabled = true },
  { execution.type = "RestartStack", execution.params.stack = "infisical-agent_maboi", execution.params.services = [], enabled = true },
  { execution.type = "RestartStack", execution.params.stack = "infisical-agent_paiki", execution.params.services = [], enabled = true }
]

##

[[alerter]]
name = "discord"
[alerter.config]
enabled = true
endpoint.type = "Discord"
endpoint.params.url = "[[DISCORD_ALERTER_WEBHOOK]]"

##

[[builder]]
name = "littlebuddy"
[builder.config]
type = "Server"
params.server_id = "littlebuddy"

##

[[resource_sync]]
name = "Global Backup TOML"
[resource_sync.config]
linked_repo = "infra.stacks"
resource_path = [
  "./platform/komodo/files/komodo-config-sync.toml"
]
managed = true