...@_config

classes: {
  service: {
    shape: rectangle
    style: {
      fill: "#1e293b"
      stroke: "#475569"
      font-color: "#f1f5f9"
      border-radius: 6
    }
  }
  role: {
    style.stroke-dash: 3
  }
  datastore: {
    shape: cylinder
    style.fill: "#0f766e"
  }
}

hosts: Hosts {
  remote: Remote {
    mesh: Mesh {
      meshp: Mesh Provider {
        class: role
        netbird: NetBird
      }
    }
    edge: Edge {
      edgep: Edge Provider {
        class: role
        pangolin: Pangolin
      }
    }
    core: Core {
      contm: Container Manager {
        class: role
        komodo: Komodo
      }
      secp: Secrets Provider {
        class: role
        infisical: Infisical
      }
      idp: Identity Provider {
        class: role
        authentik: Authentik
      }
      gitForge: Git Forge {
        class: role
        forgejo: Forgejo
      }
      ciPipe: CI/CD Pipeline {
        class: role
        woodpecker: Woodpecker
      }

      gitForge.forgejo -> ciPipe.woodpecker
    }
  }

  local: Local {
    workerLIL: worker_littlebuddy {
      dashboard: Dashboard {
        class: role
        homarr: Homarr
      }
      apps: Apps {
        class: role
        paper: Paperless
        openprj: OpenProject
      }
      dbMain: Main Database {
        class: role
        postgres: Postgres {
          class: datastore
        }
      }
      automation: Automation {
        class: role
        neightn: N8N
      }

      apps.openprj -> dbMain.postgres
      apps.paper -> dbMain.postgres
    }

    workerBIG: worker_biggy {
      gameServers: Game Servers {
        class: role
        terraria: Terraria {
          data: |yml
            Data:
              - /srv/docker/files/terraria
          |
        }
      }
      fileBrowse: File Browser {
        class: role
        fbq: File Browser Quantum
      }
      ciAgent: CI Agent {
        class: role
        woodpeckerAgent: Woodpecker Agent
      }

      fileBrowse.fbq -> gameServers.terraria.data
    }

    workerBIL: worker_bill

    media: media_paiki {
      stream: Stream {
        class: role
        plex: Plex
        arr: "*arr"
      }
      personal: Personal {
        class: role
        immich: Immich
      }
    }

    storage: storage_snaszy {
      bakMan: Backup Managers {
        class: role
        databasus: Databasus
        zerobyte: Zerobyte
      }
      dataStores: Data Stores {
        class: role
        volume1: volume1 {
          class: datastore
          backups: ../backups
          immich: ../immich
        }
      }
    }

    storage.bakMan.databasus -> workerLIL.dbMain.postgres
    media.personal.immich -> storage.dataStores.volume1.immich
  }

  remote.core.ciPipe.woodpecker -> local.workerBIG.ciAgent.woodpeckerAgent
}
