services:
  app:
    image: docker.gitea.com/gitea:${GITEA__VERS_TAG:?err}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - gitea-data:/data
    env_file:
      - "../container-envs/${GITEA__NAME:?err}.env"
    restart: on-failure:${GITEA__MAX_RESTART_ATTEMPS:?err}
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:3000/" ]
      interval: 15s
      timeout: 5s
      retries: 10
    expose:
      - '3000'
      - '22'
    networks:
      - default
      - proxy
    labels:
      traefik.enable: 'true'
      traefik.http.routers.gitea.rule: 'Host(`gitea.homektb.com`) || Host(`gitea.lilbud.homektb.com`)'
      traefik.http.routers.gitea.entrypoints: websecure
      traefik.http.routers.gitea.tls: 'true'
      traefik.http.services.gitea.loadbalancer.server.port: '3000'
      # --- SSH (raw TCP) ---
      traefik.tcp.routers.gitea-ssh.rule: 'HostSNI(`*`)'
      traefik.tcp.routers.gitea-ssh.entrypoints: gitea-ssh
      traefik.tcp.services.gitea-ssh.loadbalancer.server.port: '22'

  db:
    image: docker.io/library/postgres:${POSTGRES__VERS_TAG:?err}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - "../container-envs/${POSTGRES__NAME:?err}.env"
    restart: on-failure:${POSTGRES__MAX_RESTART_ATTEMPS:?err}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --username=${GITEA__POSTGRES_USER:?err}" ]
      interval: 5s
      timeout: 10s
      retries: 10
    expose:
      - '5432'

networks:
  proxy:
    name: proxy
    external: true

volumes:
  gitea-data: {}
  postgres-data: {}
