---
name: postgres
---

networks:
  db-backups:
    name: db-backups
    external: true
  default:
    name: "postgres"

volumes:
  db: {}

---

services:
  db:
    image: postgres:18
    profiles: [ 'full', "no_pgadmin" ]
    volumes:
      - db:/var/lib/postgresql
    restart: always
    networks:
      default:
        aliases:
          - postgres
      db-backup-shared:
        aliases:
          - postgres
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -h localhost -d postgres
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:9.13
    profiles: [ 'full' ]
    ports:
      - '5050:80'