name: postgres

services:
  db:
    image: postgres:18
    profiles: [ 'full', "no_pgadmin" ]
    volumes:
      - db:/var/lib/postgresql
    restart: always
    networks:
      default:
        aliases:
          - postgres-shared
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -h localhost -d postgres
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:9.13
    profiles: [ 'full' ]
    ports:
      - '5050:80'

networks:
  db-backup-shared:
    name: databasus_littlebuddy_db-backup-shared
    external: true
  default:    # override default name and set COMPOSE_PROJECT_NAME prefix to match default compose behavior
    name: "${COMPOSE_PROJECT_NAME}_shared"

volumes:
  db: