---
services:
  scriberr:
    image: ghcr.io/rishikanthc/scriberr@sha256:9e36448fb5a6003b28cd3d9ac783e8cbef5ed916936c20ec353a55fa380484f4
    container_name: ${COMPOSE_PROJECT_NAME}_scriberr
    volumes:
      - type: volume
        source: scriberr-data
        target: /app/data
      - type: volume
        source: scriberr-whisperx-env
        target: /app/whisperx-env
    restart: unless-stopped

volumes:
  scriberr-data:
  scriberr-whisperx-env:
