---
name: n8n-staging

services:
  n8n:
    container_name: ${COMPOSE_PROJECT_NAME}_n8n
    volumes:
      - ${DOCKER_VOLUMES}/apps/n8n/data/.n8n:/home/node/.n8n
      - ${DOCKER_VOLUMES}/apps/n8n/data/local-files:/files
    env_file:
      - ./envs/staging.env
    ports:
      - '5679:5678'
