---
name: syncthing-production

services:
  syncthing:
    env_file:
      - ./envs/production.env
    ports:
      - '8384:8384'
      - '21027:21027/udp'
      - '22000:22000/tcp'
      - '22000:22000/udp'
