---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: ${COMPOSE_PROJECT_NAME}_syncthing
    volumes:
      - type: volume
        source: syncthing-config
        target: /config
      - type: volume
        source: syncthing-data
        target: /data
    restart: unless-stopped

volumes:
  syncthing-config:
  syncthing-data:
