---
services:
  dns-server:
    image: technitium/dns-server:14.3.0
    container_name: dns-server
    depends_on:
      stop-resolved:
        condition: service_completed_successfully
    volumes:
      - ${DOCKER_VOLUMES}/network/dns-server/config:/etc/dns
    environment:
      DNS_SERVER_DOMAIN: dns-server
      DNS_SERVER_WEB_SERVICE_HTTP_PORT: 5380
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '5380:5380/tcp'
    restart: unless-stopped
    user: "0:0"
    hostname: dns-server
    profiles: [ "dns-server" ]
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535

  stop-resolved:
    image: alpine:3.23.3
    container_name: stop-resolved
    volumes:
      - /:/host
    network_mode: host
    entrypoint:
      - chroot
      - /host
      - /bin/bash
      - -c
      - |
        systemctl disable systemd-resolved
        systemctl stop systemd-resolved
        echo "systemd-resolved disabled on host"
    restart: "no"
    pid: host
    privileged: true
    profiles: [ "dns-server" ]
