services:
  app:
    image: docker.io/busybox:1.38.0
    container_name: containername
    volumes:
      - volly:/data
    networks:
      - netty
    command: ["sleep", "infinity"]
    env_file:
      - ./container.env

volumes:
  volly:
    name: vollyname

networks:
  netty:
    name: nettyname