name: ${APP__NAME:?err}

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_internal
  postgres_shared:
    name: postgres_shared
    external: true

volumes:
  assets: {}

services:
  autoheal:
    image: willfarrell/autoheal:${AUTOHEAL__VERSION:?err}
    env_file:
      - "../container-envs/autoheal.env"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  cache:
    image: memcached
    restart: unless-stopped

  cron:
    image: openproject/openproject:${APP__VERSION:?err}
    depends_on:
      - cache
      - seeder
    env_file:
      - "../container-envs/${APP__NAME:?err}.env"
    volumes:
      - type: volume
        source: assets
        target: /var/openproject/assets
    command: "./docker/prod/cron"
    restart: unless-stopped
    networks:
      - default
      - postgres_shared

  hocuspocus:
    image: openproject/hocuspocus:${HOCUSPOCUS__VERSION:?err}
    ports:
      - '1234:1234'
    restart: unless-stopped

  seeder:
    image: openproject/openproject:${APP__VERSION:?err}
    env_file:
      - "../container-envs/${APP__NAME:?err}.env"
    volumes:
      - type: volume
        source: assets
        target: /var/openproject/assets
    command: "./docker/prod/seeder"
    restart: on-failure
    networks:
      - default
      - postgres_shared

  web:
    image: openproject/openproject:${APP__VERSION:?err}
    depends_on:
      - cache
      - seeder
    env_file:
      - "../container-envs/${APP__NAME:?err}.env"
    volumes:
      - type: volume
        source: assets
        target: /var/openproject/assets
    command: "./docker/prod/web"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health_checks/default" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 60s
    labels:
      - autoheal=true
    ports:
      - '8080:8080'
    networks:
      - default
      - postgres_shared

  worker:
    image: openproject/openproject:${APP__VERSION:?err}
    depends_on:
      - cache
      - seeder
    env_file:
      - "../container-envs/${APP__NAME:?err}.env"
    volumes:
      - type: volume
        source: assets
        target: /var/openproject/assets
    command: "./docker/prod/worker"
    restart: unless-stopped
    networks:
      - default
      - postgres_shared
